/**
 * UNLAWYERED — shared contracts between server and web.
 * Single source of truth for API payloads (zod schemas) and TS types.
 */
import { z } from "zod";

/* ------------------------------------------------------------------ */
/* Providers                                                          */
/* ------------------------------------------------------------------ */

export const PROVIDER_IDS = ["gemini", "openai", "anthropic", "mock"] as const;
export type ProviderId = (typeof PROVIDER_IDS)[number];

export const ProviderIdSchema = z.enum(PROVIDER_IDS);

export const DEFAULT_MODELS: Record<ProviderId, string> = {
  gemini: "gemini-2.0-flash",
  openai: "gpt-4o-mini",
  anthropic: "claude-3-5-haiku-latest",
  mock: "mock-1",
};

/** Shown in the footer of every page and inside every AI result. */
export const LEGAL_DISCLAIMER =
  "UNLAWYERED provides legal information generated by AI, not legal advice. " +
  "It does not create an advocate–client relationship. AI output may be " +
  "incomplete, outdated, or wrong — verify against primary sources and " +
  "consult a qualified advocate for advice on your situation.";

export interface ProviderInfo {
  id: ProviderId;
  label: string;
  /** Human-facing note shown in Settings */
  note: string;
  /** Does this provider need an API key from the user? */
  requiresKey: boolean;
  /** Does the backend currently have a usable key for this provider? */
  hasKey: boolean;
  /** If the key came from the server env rather than the Settings page */
  keySource: "settings" | "env" | "none";
}

/* ------------------------------------------------------------------ */
/* Settings                                                           */
/* ------------------------------------------------------------------ */

export const SetProviderRequestSchema = z.object({
  provider: ProviderIdSchema,
});
export type SetProviderRequest = z.infer<typeof SetProviderRequestSchema>;

export const SetKeyRequestSchema = z.object({
  provider: ProviderIdSchema,
  apiKey: z.string().trim().min(10, "That key looks too short").max(4096),
});
export type SetKeyRequest = z.infer<typeof SetKeyRequestSchema>;

export interface TestConnectionResult {
  ok: boolean;
  provider: ProviderId;
  /** e.g. "gemini-2.0-flash" */
  model?: string;
  latencyMs?: number;
  detail: string;
}

/* ------------------------------------------------------------------ */
/* Sources / citations                                                */
/* ------------------------------------------------------------------ */

export const SourceSchema = z.object({
  /** Which legal instrument / judgment this source refers to */
  title: z.string(),
  /** Canonical citation, e.g. "Art. 21, Constitution of India" or "AIR 1978 SC 597" */
  citation: z.string().optional(),
  /** Pinpoint reference the model claims, e.g. "Section 4(c)" */
  pinpoint: z.string().optional(),
  /** URL if the model supplied one (rendered as a link, verified-ish) */
  url: z.string().url().optional(),
  /** How the source is used */
  role: z.enum(["statute", "case", "secondary", "document", "other"]).default("other"),
  /** The model's one-line summary of what this source supports */
  note: z.string().optional(),
});
export type Source = z.infer<typeof SourceSchema>;

/* ------------------------------------------------------------------ */
/* AI result envelope (shared by all five tools)                      */
/* ------------------------------------------------------------------ */

export const CitationMarkerSchema = z.object({
  /** Marker text as embedded in prose, e.g. "[1]" */
  marker: z.string(),
  /** Index into `sources` */
  sourceIndex: z.number().int().nonnegative(),
});
export type CitationMarker = z.infer<typeof CitationMarkerSchema>;

export interface AiResult {
  tool: ToolId;
  provider: ProviderId;
  model: string;
  /** Markdown-formatted answer */
  answer: string;
  sources: Source[];
  /** Map of "[n]" markers found in `answer` -> source index */
  citations: CitationMarker[];
  /** True if a real provider answered; false for the Mock provider */
  liveProvider: boolean;
  latencyMs: number;
}

/* ------------------------------------------------------------------ */
/* The five tools                                                     */
/* ------------------------------------------------------------------ */

export const TOOL_IDS = [
  "explain-law",
  "ask",
  "review-document",
  "cross-check",
  "stress-test",
] as const;
export type ToolId = (typeof TOOL_IDS)[number];

/** Plain text question-style tools */
export const AskRequestSchema = z.object({
  question: z.string().trim().min(3).max(5000),
  jurisdiction: z.string().trim().max(200).default("India"),
});
export type AskRequest = z.infer<typeof AskRequestSchema>;

/** Explain a law */
export const ExplainLawRequestSchema = z.object({
  lawName: z.string().trim().min(2).max(300),
  aspect: z.string().trim().max(500).optional(),
});
export type ExplainLawRequest = z.infer<typeof ExplainLawRequestSchema>;

/** Explain a judgment */
export const ExplainJudgmentRequestSchema = z.object({
  caseName: z.string().trim().min(2).max(300),
  citation: z.string().trim().max(200).optional(),
});
export type ExplainJudgmentRequest = z.infer<typeof ExplainJudgmentRequestSchema>;

/** Document-backed tools share this */
export const DocumentInputSchema = z.object({
  name: z.string().trim().min(1).max(300),
  text: z.string().min(1).max(400_000, "Document too large (max 400k characters)"),
});
export type DocumentInput = z.infer<typeof DocumentInputSchema>;

export const ReviewDocumentRequestSchema = z.object({
  document: DocumentInputSchema,
  focus: z.string().trim().max(500).optional(),
});
export type ReviewDocumentRequest = z.infer<typeof ReviewDocumentRequestSchema>;

export const CrossCheckRequestSchema = z.object({
  document: DocumentInputSchema,
  jurisdiction: z.string().trim().max(200).default("India"),
});
export type CrossCheckRequest = z.infer<typeof CrossCheckRequestSchema>;

export const StressTestRequestSchema = z.object({
  document: DocumentInputSchema,
  side: z.enum(["my", "other"]).default("my"),
  concern: z.string().trim().max(500).optional(),
});
export type StressTestRequest = z.infer<typeof StressTestRequestSchema>;

/* ------------------------------------------------------------------ */
/* Documents (upload)                                                 */
/* ------------------------------------------------------------------ */

/** Shared 30 MB upload cap — enforced client-side (instant rejection) and
 *  server-side (multer limit + extension/size assertion). One constant, two
 *  enforcement points; changing it here changes both. */
export const MAX_UPLOAD_BYTES = 30 * 1024 * 1024;

export interface UploadedDocument {
  id: string;
  name: string;
  sizeBytes: number;
  characters: number;
  /** First ~200 chars so the UI can preview without storing everything */
  preview: string;
  createdAt: string;
}
